people=['mom','dad','sister']
print("Now there will be a larger dining-table.")
people.insert(0,'brother')
people.insert(2,'friend')
people.append('teacher')
print("Dear "+people[0]+", I'd like to invite you to have dinner with me on Friday at my home.")
print("Dear "+people[1]+", I'd like to invite you to have dinner with me on Friday at my home.")
print("Dear "+people[2]+", I'd like to invite you to have dinner with me on Friday at my home.")
print("Dear "+people[3]+", I'd like to invite you to have dinner with me on Friday at my home.")
print("Dear "+people[4]+", I'd like to invite you to have dinner with me on Friday at my home.")
print("Dear "+people[5]+", I'd like to invite you to have dinner with me on Friday at my home.")